#!/usr/bin/env python3
"""Generate sitemap.xml for demo.retrovault.world.

Every game in the Vault is the same game.html with a different ?id=, so search
engines have no way to discover them by following links alone - the shelf grid
is built by JavaScript after the page loads. This writes them out explicitly.

Run it from the vault root after adding games:

    python3 tools/make_sitemap.py

games.js is a JSON object behind one `window.GAMES_DATA = ` assignment, so it
parses directly once that wrapper is stripped - no JS engine needed, same
approach the rest of tools/ takes.
"""

import io
import json
import os
import re
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "https://demo.retrovault.world"

# Pages that exist as real files, rather than as a ?id= on game.html.
STATIC = [
    ("/", "weekly", "1.0"),
    ("/resources.html", "monthly", "0.6"),
]


def games():
    raw = io.open(os.path.join(ROOT, "games.js"), encoding="utf-8").read()
    body = re.sub(r"^\s*window\.GAMES_DATA\s*=\s*", "", raw.strip())
    body = re.sub(r";\s*$", "", body)
    return json.loads(body)["games"]


def esc(v):
    return (v.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace('"', "&quot;").replace("'", "&apos;"))


def main():
    today = date.today().isoformat()
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           "<!-- Generated by tools/make_sitemap.py - do not hand-edit. -->",
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']

    for path, freq, pri in STATIC:
        out += ["  <url>",
                "    <loc>%s%s</loc>" % (BASE, path),
                "    <lastmod>%s</lastmod>" % today,
                "    <changefreq>%s</changefreq>" % freq,
                "    <priority>%s</priority>" % pri,
                "  </url>"]

    rows = games()
    for g in rows:
        loc = esc("%s/game.html?id=%s" % (BASE, g["id"]))
        out += ["  <url>",
                "    <loc>%s</loc>" % loc,
                "    <lastmod>%s</lastmod>" % today,
                "    <changefreq>yearly</changefreq>",
                "    <priority>0.8</priority>",
                "  </url>"]

    out.append("</urlset>")
    out.append("")
    text = "\n".join(out)
    io.open(os.path.join(ROOT, "sitemap.xml"), "w", encoding="utf-8").write(text)
    print("sitemap.xml: %d URLs (%d games + %d static)"
          % (len(rows) + len(STATIC), len(rows), len(STATIC)))


if __name__ == "__main__":
    main()
