#!/usr/bin/env python3
"""Generate sitemap.xml for demo.retrovault.world.

The URLs listed here are the pre-rendered pages in game/, written by
tools/make_gamepages.py - not game.html?id=. Those two are the same page, and
the generated one is the address worth indexing, because its title, description
and canonical are in the served HTML rather than written by JavaScript after
the fact. Listing the ?id= form as well would just ask Google to spend 396
fetches on URLs that canonicalise away.

Run BOTH, from the vault root, after adding games - the sitemap second, since
it lists files the other one writes:

    python3 tools/make_gamepages.py
    python3 tools/make_sitemap.py

games.js is a JSON object behind one `window.GAMES_DATA = ` assignment, so it
parses directly once that wrapper is stripped - no JS engine needed, same
approach the rest of tools/ takes.
"""

import io
import json
import os
import re
from datetime import date
from urllib.parse import quote

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "https://demo.retrovault.world"

# Pages that exist as real files, rather than as a ?id= on game.html.
STATIC = [
    ("/", "weekly", "1.0"),
    ("/catalogue.html", "weekly", "0.9"),
    ("/resources.html", "monthly", "0.6"),
]


def games():
    raw = io.open(os.path.join(ROOT, "games.js"), encoding="utf-8").read()
    body = re.sub(r"^\s*window\.GAMES_DATA\s*=\s*", "", raw.strip())
    body = re.sub(r";\s*$", "", body)
    return json.loads(body)["games"]


def esc(v):
    return (v.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace('"', "&quot;").replace("'", "&apos;"))


def main():
    today = date.today().isoformat()
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           "<!-- Generated by tools/make_sitemap.py - do not hand-edit. -->",
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']

    for path, freq, pri in STATIC:
        out += ["  <url>",
                "    <loc>%s%s</loc>" % (BASE, path),
                "    <lastmod>%s</lastmod>" % today,
                "    <changefreq>%s</changefreq>" % freq,
                "    <priority>%s</priority>" % pri,
                "  </url>"]

    rows = []
    skipped = 0
    for g in games():
        name = "game/%s.html" % g["id"]
        path = os.path.join(ROOT, name)
        if not os.path.exists(path):
            raise SystemExit(
                "%s is missing - run tools/make_gamepages.py first" % name)
        # Only list pages that claim to be their own canonical. An alternate
        # dump's page points at its primary instead, and a sitemap that lists
        # a URL which canonicalises elsewhere is asking a crawler to spend a
        # fetch discovering that it was pointed at the wrong address.
        html = io.open(path, encoding="utf-8").read()
        m = re.search(r'<link rel="canonical" href="([^"]+)">', html)
        self_url = "%s/game/%s.html" % (BASE, quote(g["id"], safe=""))
        if not m or m.group(1) != self_url:
            skipped += 1
            continue
        rows.append(g)
        out += ["  <url>",
                "    <loc>%s</loc>" % esc(self_url),
                "    <lastmod>%s</lastmod>" % today,
                "    <changefreq>yearly</changefreq>",
                "    <priority>0.8</priority>",
                "  </url>"]

    out.append("</urlset>")
    out.append("")
    text = "\n".join(out)
    io.open(os.path.join(ROOT, "sitemap.xml"), "w", encoding="utf-8").write(text)
    print("sitemap.xml: %d URLs (%d games + %d static; %d alternates skipped, "
          "they canonicalise to their primary)"
          % (len(rows) + len(STATIC), len(rows), len(STATIC), skipped))


if __name__ == "__main__":
    main()
